---
version: "2"
plugins:
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD024:
        enabled: false
      MD033:
        enabled: false
  fixme:
    enabled: true